[project]
name = "fgosccnt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-contrib-python>=4.12.0.88",
    "pytesseract>=0.3.13",
]
